### ISSUE TITLE
Unable to change current drive using "Letter:" syntax, cd/pushd on drive with empty path ("Letter:") broken

### ISSUE THREAD

**Issue by TheKvc** [darkbatcher/picobat#5]
I am using google Drive for desktop (Mounted as G: , H:, J:, K: ) and one more ubuntu (v20.04) folder is shared via network (as Y: Drive)
![image](https://github.com/darkbatcher/picobat/assets/46124093/7a12318a-6695-4b24-9817-17a2935974bf)

When I am trying to PUSHD or CD into them with CMD/windows terminal... it works pretty fine. and i can navigate into the folders via command line.

![image](https://github.com/darkbatcher/picobat/assets/46124093/f2b4309f-f744-44ba-8e03-595c2fadf191)

but picobat is having some issues, when i try to do the same:
![image](https://github.com/darkbatcher/picobat/assets/46124093/b191024e-b219-4c75-9379-607554b83a91)

MY SYSTEM:
![image](https://github.com/darkbatcher/picobat/assets/46124093/5a7e0e79-abfd-49a2-903a-04957af1b407)

**Comment by TSnake41** [comment]
The problem is not really not being able to cd into network shares (which works) but rather that cd/pushd into paths that doesn't have a trailing backslash.

In my testing, `cd Y:\` do works, although, `cd Y:` doesn't, regardless of whether is it a network share or not. Drive command is also broken (although, it is possible to workarround by making aliases)
Idealy, Y:\ and Y: should be functionnaly equivalent.

A funny thing is that paths without trailing backslahes have some confusing behaviors in cmd, such as
```batch
rem Assuming %userprofile% is in C:
cd /d %userprofile%
cd /d E:\

rem dir C: is displaying %userprofile% content
dir C:
```

**Comment by TheKvc** [comment]
@TSnake41 
> In my testing, `cd Y:\` do works, although, `cd Y:` doesn't, regardless of whether is it a network share or not.

Yes, you are absolutely right, I just realized that too... And the funny thing is that if I use the proper switch then I don't even need to use that trailing backward slash... 
![image](https://github.com/darkbatcher/picobat/assets/46124093/d0e57256-6c9a-4a51-a807-402c28b0a6f3)




> Idealy, Y:\ and Y: should be functionnaly equivalent.
This is the expected behavior that I wanted from Picobat, As I'm using Ubuntu side by windows 11 and I want to test my scripts in both the systems and Picobat is going to be the platform for my testing... Thank you guys for creating this masterpiece.




> A funny thing is that paths without trailing backslahes have some confusing behaviors in cmd, such as

Yes I just realized that by testing and I think CMD also has this \ issue... But since it has never gave error like Picobat is giving so we assume that we need to change the command directly and we don't see it as an issue...

![image](https://github.com/darkbatcher/picobat/assets/46124093/8427ffb6-4d36-4ece-9c84-73e49cca992f)

**Comment by darkbatcher** [comment]
Hello,

Does it mean that `c:` is the shorthand for `c:\{current dir}` ? I thought this was implemented though.
I'm working on a patch

Edit: I checked the source, `cd x:` works, however it needs the variable `=x:` (which stores the current directory of drive `x` even on `cmd`)to be set to work properly otherwise it fails trying to access `c:`.
There is at least two problems :
* At startup, the  variable associated with current drive is not set
* When the variable `=x:` is not set, a bug make it so that `cd x:` fails by looking for `x:` instead of `x:\`

**Comment by darkbatcher** [comment]
Hello,

Ok i have a fix for points for both points I mentionned above (current drive drive environment variable `=x:` initialisation and also the `x:` bug)

But i wonder if we should support the `C:` gimmick. Besides i just saw on ss64.com that `CD x:` should display curent path of `X:`

**Comment by TheKvc** [comment]
> But i wonder if we should support the `C:` gimmick. Besides i just saw on ss64.com that `CD x:` should display curent path of `X:`

in my opinion, i have 2 thoughts....

1. this seems like a bug of cmd. but, if someone uses that feature/bug of cmd in their program to get its functionality to use in action - then running the same script in picobat must provide the similar behaviour in order to maintain compatibility. 
2. CMD is buggy, and as picobat is a better version of cmd (you should also have a look at nushell, it has the similar thought behind its making) - so it should have better features and less bugs.

both seems to be paradoxical. Basically, there is a trade-off with any choice.
