### ISSUE TITLE
Path name is case sensitive on linux (ubuntu 22)

### ISSUE THREAD

**Issue by TheKvc** [darkbatcher/picobat#6]
![Screenshot from 2024-02-09 18-49-18](https://github.com/darkbatcher/picobat/assets/46124093/9f0354be-7eb9-4bc1-99a4-b215aa9d2c23)

When i am trying to navigate to my '_Temp ' folder... the sutocomplete feature of picobat has no issues with the "t" (small T) and "T" (Capital T)... but as linux (ubuntu 22) uses case sensitive pathnames... the simple CD with picoBat didn't work,

Let me know, if you need additional info from my side...

**Comment by TSnake41** [comment]
This is intentional as paths are case insensitive on Linux e.g you can have both "Test" and "test" directories in a same path that will be different directories.

If you really need a Windows-compatible behavior, you can try to have a mount point mounted as case-insensitive (e.g [ext4 casefold](https://www.collabora.com/news-and-blog/blog/2020/08/27/using-the-linux-kernel-case-insensitive-feature-in-ext4/), lowntfs-3g with ignore_case, vfat/exfat partition, ciopfs, ...)

**Comment by TheKvc** [comment]
I understand what you're saying but for example while making a batch file we barely care about the case sensitivity of the path and folders and filenames. 

I get your point, but at the same time there should be some in between method that can warn the user about the sensitivity of the names. I think this thread should be closed because I cannot think of any middle ground in between which can help us out with making the path sensitivity and insensitivity in windows compatible.
